# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_features <- function(ifile) {
    invisible(.Call('_neurostrcpp_compute_features', PACKAGE = 'neurostrcpp', ifile))
}

random_branch <- function() {
    .Call('_neurostrcpp_random_branch', PACKAGE = 'neurostrcpp')
}

random_barycenter <- function() {
    .Call('_neurostrcpp_random_barycenter', PACKAGE = 'neurostrcpp')
}

random_node <- function() {
    .Call('_neurostrcpp_random_node', PACKAGE = 'neurostrcpp')
}

timesTwo <- function(x) {
    .Call('_neurostrcpp_timesTwo', PACKAGE = 'neurostrcpp', x)
}

