# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

random_branch <- function() {
    .Call('_neurostrcpp_random_branch', PACKAGE = 'neurostrcpp')
}

#' Compute branch features
#'
#' @export
compute_branch_features <- function(ifile) {
    .Call('_neurostrcpp_compute_branch_features', PACKAGE = 'neurostrcpp', ifile)
}

random_barycenter <- function() {
    .Call('_neurostrcpp_random_barycenter', PACKAGE = 'neurostrcpp')
}

random_node <- function() {
    .Call('_neurostrcpp_random_node', PACKAGE = 'neurostrcpp')
}

#' Compute node features
#'
#' @export
compute_node_features <- function(ifile) {
    .Call('_neurostrcpp_compute_node_features', PACKAGE = 'neurostrcpp', ifile)
}

timesTwo <- function(x) {
    .Call('_neurostrcpp_timesTwo', PACKAGE = 'neurostrcpp', x)
}

