# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute branch features
#'
#' @export
compute_branch_features <- function(ifile, omitapical = FALSE, omitaxon = FALSE, omitdend = FALSE, correct = FALSE, selection = "all") {
    .Call('_neurostr_compute_branch_features', PACKAGE = 'neurostr', ifile, omitapical, omitaxon, omitdend, correct, selection)
}

#' Compute node features
#'
#' @export
compute_node_features <- function(ifile, omitapical = FALSE, omitaxon = FALSE, omitdend = FALSE, correct = FALSE) {
    .Call('_neurostr_compute_node_features', PACKAGE = 'neurostr', ifile, omitapical, omitaxon, omitdend, correct)
}

#' Converts a reconstruction to SWC or JSON.
#' 
#' Use resolved paths, i.e., not with ~ for the home directory.
#'
#' @example
#' file <- system.file("extdata/", "C030502A.swc", package = "neurostr")
#' convert(file, ext = "swc")
#' @export
convert <- function(ifile, ext, eps = 0.0, correct = FALSE) {
    .Call('_neurostr_convert', PACKAGE = 'neurostr', ifile, ext, eps, correct)
}

#' Compute branch features
#'
#' @export
validate <- function(ifile) {
    .Call('_neurostr_validate', PACKAGE = 'neurostr', ifile)
}

